### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by linuxscout** [projeduc/ESI_2CS_TALN#12]
Salam,

I read some pages, I found some issue,

* page xvii: 
   *  IA international business machines  => **IBM**
*  Page 2: same error on peut mentionner international business machines (IA) => **IBM**
* References are not readable in paper when printed
* page 3 : "Afin de supporter cette **approches**"
* page 7: "dans cette **phrase*** on peut dédier ", I think it should be "phase"
* page 7: 

> Langues agglutinantes : les morphèmes sont toujours clairement différentiables phonéti-
quement l’un de l’autre. Parmi ces langues : finnois, turc, japonais, langues berbères, etc..

an example for berber langages as agglutinative, is suitable
* page 8:

> Vous pouvez savoir plus sur ces traits en suivant ce lien : https://universaldependencies.
org/u/feat/index.html .

I think it's suitable to put it as footnote.

* page  8
>Cas : représente le rôle sémantique **pa rapport** au verbe. nominatif (sujet d’un verbe), accusatif (objet
direct), datif (objet indirect), etc.

par rapport
* page 8

> Aspect : accompli(une action qui a été accomplie dans le temps)/inaccompli, progressif (une action
qui est continue dans le temps), imperfectif (une action qui a pris une certaine période dans le temps
mais on ne sait pas si elle est complète)/perfectif, itératif (une action qui se répète), prospectif (une
action qui devrait avoir lieu à un moment qui suit un point de référence), etc.
— Voix (diathèse) : décrit comment s’organisent les rôles sémantiques par rapport au verbe. active (le
sujet est l’agent ; celui qui a fait l’action), moyenne (le sujet est l’agent et le patient au même temps ;
faire une action sur lui-même), passive (le sujet est le patient ; celui qui reçut l’action), réciproque
(des agents et des patients qui font des actions l’un sur l’autre), etc.

I propose to put sub itemize to enumerate different features.

* page 9

> Troncation : Exemple, bibliographie, biblio, information, info, **fish (N), to fish (V)**

to remove last part

* page 9

> une phrase est constituée de plusieurs **syntagme s** qui sont constitués des mots et d’autres **syntagme s**

a space after "syntagme" word

* page 9
* 

> Pour plus de relations vous pouvez consulter : https://universaldependencies.org/u/dep/index.html .

to put as footnote

I arrived here, I will send more notes as reading.

**Comment by kariminf** [comment]
Salam, 
Thank you for this precious revision. 

As for berber language, I'm not sure if it is agglunative; I tried to look for examples, but it seems to me as a flectional language. So, I decided to delete it from agglunative list till I am sure about its categorization. 

For the sub-items, I avoided them so the chapter's size won't be so big (the introduction is big compared to other chapters except the last one)
